### ISSUE TITLE
Ubuntu build error....

### ISSUE THREAD

**Issue by frohro** [pockemul/PockEmul#24]
It would be nice to have some build instructions.  Using the pockemu.pro with Qt5.4, on Ubuntu 15.05 I get the following:
:-1: error: [build/rcc/qrc_jr800.cpp] Error 1
this directory isn't there and I find no qrc_jr800.cpp anywhere.

**Comment by frohro** [comment]
I looked at the compile output, and it is missing the ROM file.

RCC: Error in '../PockEmul/resources/jr800.qrc': Cannot find file 'jr800/rom-8000-FFFF.bin'

That file appears in QtCreator's Resources/resources/jr800.qrc/  so in an external editor I deleted the line from the jr800.qrc and am building again.  I don't intend to use the jr800, so for me this will work.

**Comment by pockemul** [comment]
Hi,
The JR-800 is a very rare computer. No emulator exist for this model because of the lack on ROM dump.
That's why i wanted to keep this ROM secret until Pockemul emulate correctly the JR-800.
I realize that this attitude is completely immature :-).
I've just push the missing file into the repository.

regards
